version: '3.9'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "6060:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - SELENIUM_REMOTE_HOST=selenium-hub
    depends_on:
      - db
      - redis
  celery:
    build: .
    command: celery -A config worker -l INFO
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
      - selenium-hub
      - firefox
      - celery-beat
  celery-beat:
    build: .
    command: celery -A config beat -l info
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
  db:
    image: postgres:14
    container_name: postgres #you can change this
#    restart: always
    environment:
      - POSTGRES_USER=erfan
      - POSTGRES_PASSWORD=erfan # Corrected the variable name from PASS to PASSWORD
      - POSTGRES_DB=job_linker
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
  pg-admin:
    container_name: pgadmin_1
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=erfan@erfan.com
      - PGADMIN_DEFAULT_PASSWORD=erfan

    ports:
      - "5050:80"
  firefox:
    image: selenium/node-firefox:dev
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
volumes:
  postgres_data:




