version: '3.9'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - redis
  celery:
    build: .
#    command: celery --app=config worker --loglevel=info  # تغییر در دستور اجرای celery worker
    command: celery -A config worker -l INFO
    volumes:
      - .:/code
    depends_on:
      - web
      - redis

  db:
    image: postgres:14
    container_name: postgres_1 #you can change this
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root # Corrected the variable name from PASS to PASSWORD
      - POSTGRES_DB=django_erfan
#      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
  pg-admin:
    container_name: pgadmin_1
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@root.com
      - PGADMIN_DEFAULT_PASSWORD=root

    ports:
      - "5050:80"
  redis:
    image: "redis:alpine"
volumes:
  pgdata:


