version: '3.9'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000

  db:
    image: postgres:14
    container_name: postgres_1 #you can change this
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root # Corrected the variable name from PASS to PASSWORD
      - POSTGRES_DB=django_erfan
#      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
  pg-admin:
    container_name: pgadmin_1
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@root.com
      - PGADMIN_DEFAULT_PASSWORD=root

    ports:
      - "5050:80"
