# Generated by Django 4.2.3 on 2023-08-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='company_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='date_modified',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='description_position',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='detail_position',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='website',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
