# Generated by Django 4.2.3 on 2023-08-01 11:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_company_name_post_date_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_crawled',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_modified',
            field=models.IntegerField(blank=True),
        ),
    ]
